Update capacity.py
Explained issue and means of fixing this error in comments:
File "C:\Users\sergius\Desktop\Scripts\Scripts\noahscriptsmergedandworking\capacity.py", line 91, in inlet_control
    Qf += valid_rows[cur_culvert_index + offset]['Qc']
IndexError: list index out of range

Flags culvert addition currently requires culverts to be pre-sorted.